### ISSUE TITLE
Lambda function is too big

### ISSUE THREAD

**Issue by gawlk** [ARautio/aws-lambda-pdf-generator-puppeteer#3]
Hi,

I'm pretty new to all this AWS thing but I tried to clone and deploy it but I get this message

```
An error occurred: PdfLambdaFunction - Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 072a791b-6269-4eb0-9cb2-7233dfade786).
```

Am I missing something or is there indeed a problem ?

Thank you

**Comment by ARautio** [comment]
The issue you are having in here is because the package which is uploaded as lambda functions exceeds 250MB. I have seen that this setup usually takes roughly 50 MB (and around 120MB when unpacked) that should fit pretty well so something huge is included with your deployment.

I saw this same thing happening when trying things out and for me the issue was that my earlier test installed full chromium which was huge. In your case it might be something else.

The easiest way to debug this is to check the zuo package inside .serverless/ directory and check why it contains.

**Comment by gawlk** [comment]
I'm not sure what I did exactly but after following exactly your tutorial again, everything is fine ! Thank you !

**Comment by gawlk** [comment]
I just followed your guide step by step, with a clean setup and I still got the error.

What's weird is that .serverless weighs indeed around 120MB ! 

Here's more of the output if it can help

```
Serverless: Safeguards Summary: 5 passed, 2 warnings, 0 errors
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service pdf.zip file to S3 (109.5 MB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...........................................
Serverless: Operation failed!
Serverless: View the full error output: https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-central-1%3A728219310727%3Astack%2Fpdf-development%2F844d9860-afe9-11ea-b0a5-0a176ee37dc4
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Successfully published your service to the Serverless Dashboard: https://dashboard.serverless.com/tenants/gawlk/applications/pdftest/services/pdf/stage/development/region/eu-central-1
 
  Serverless Error ---------------------------------------
 
  An error occurred: PdfLambdaFunction - Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 8766c2ca-a133-434d-8f78-6b255fd4e648).
```
